### ISSUE TITLE
Can u tell me Where can I find this module?

### ISSUE THREAD

**Issue by pwrusr** [numeprenume/Xperia-Tweaks#1]

**Comment by numeprenume** [comment]
I haven't published it anywhere and I don't plan to as it's just for private use, but feel free to compile it if you wish.

**Comment by pwrusr** [comment]
Can u send me ur mail.. I'm willing to publish it.. 
So I can add author card (: 

praviipravallika@gmail.com

**Comment by numeprenume** [comment]
Thanks but no, if I wanted to publish it I would do it myself. Maybe one day, but not now as it's far from finished and it doesn't really have a direction right now, it's just random things I needed at a specific time.

**Comment by pwrusr** [comment]
Seems someday in future our Xperias will be getting some more support (: 
#ot.. Can u send me ss of nify with the changes u made nw (: 
Thank you...

**Comment by pwrusr** [comment]
can u pls suggest me the app which can extract full code with line-line edit..,,apk studio which ws running fine from half a year .....nw refuses to go smooth on my lap

**Comment by numeprenume** [comment]
I only use command-line apktool and Notepad++ for editing smali.
